var fs = require('fs');
module.exports = function(file) {
    var fileToMakeArray = file;
    var fileToMake = fileToMakeArray[0];
    if(fileToMake != undefined || fileToMakeArray != []) {
        fs.writeFile(fileToMake, '/* File Generated by OWL */');
    }
    
};