var fs = require('fs');
module.exports = function(file) {
    var fileToMakeArray = file;
    var fileToMake = fileToMakeArray[0];
    if(fileToMake != undefined || fileToMakeArray != []) {
        console.log('\x1b[32m', 'Owl is making a file' ,'\x1b[0m');
        fs.writeFile(fileToMake, '/* File Generated by OWL */');
    }
    
};